# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  
trigger:
- main

pool:
  name: 'TestAgent'

resources:
  repositories:
    - repository: pipeline_templates
      endpoint: quangpham1019 (2)
      type: github
      name: quangpham1019/pipeline-experiment

steps:
- script: echo Trying to parse template from another repo
- template: common-pipeline-1.yml@pipeline_templates
