# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
    - repository: pipeline_templates
      endpoint: quangpham1019
      type: github
      name: quangpham1019/pipeline-experiment
  
trigger:
- main

pool:
  name: 'TestAgent'

steps:
- checkout: pipeline_templates
- template: azure-pipelines.yml@pipeline_templates
